#!/bin/bash
# JARVIS Interface Options

echo "🤖 JARVIS Interface Options"
echo "============================"
echo ""
echo "1. 💻 Terminal CLI (Recommended)"
echo "   • Gemini CLI / Claude Code style interface"
echo "   • Runs directly in terminal with rich formatting"
echo "   • Elegant panels and natural conversation flow"
echo "   • Launch: python jarvis_cli.py"
echo ""
echo "2. 💻 Classic Terminal"
echo "   • Traditional command-line interface"
echo "   • Direct JARVIS interaction"
echo "   • Launch: python jarvis.py"
echo ""
echo "🚀 Quick Launch:"
echo "   Terminal CLI: ./launch_tui.sh"
echo "   Classic:      python jarvis.py"
